[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = ["python -m ensurepip --upgrade", "python -m pip install -r requirements.txt"]

[start]
cmd = "python download_models.py && uvicorn main:app --host 0.0.0.0 --port $PORT"
